//-----------------------------------------------------------------------
// <copyright file="GlobalSuppressions.cs">(c) http://TfsBuildExtensions.codeplex.com/. This source is subject to the Microsoft Permissive License. See http://www.microsoft.com/resources/sharedsource/licensingbasics/sharedsourcelicenses.mspx. All other rights reserved.</copyright>
//-----------------------------------------------------------------------
// <autogenerated/>
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1051:DoNotDeclareVisibleInstanceFields", Scope = "member", Target = "TfsBuildManager.Repository.BuildRetentionPolicy.#SucceededKeep")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1051:DoNotDeclareVisibleInstanceFields", Scope = "member", Target = "TfsBuildManager.Repository.BuildRetentionPolicy.#SucceededDeleteOptions")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1051:DoNotDeclareVisibleInstanceFields", Scope = "member", Target = "TfsBuildManager.Repository.BuildRetentionPolicy.#StoppedKeep")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1051:DoNotDeclareVisibleInstanceFields", Scope = "member", Target = "TfsBuildManager.Repository.BuildRetentionPolicy.#StoppedDeleteOptions")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1051:DoNotDeclareVisibleInstanceFields", Scope = "member", Target = "TfsBuildManager.Repository.BuildRetentionPolicy.#PartiallySucceededKeep")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1051:DoNotDeclareVisibleInstanceFields", Scope = "member", Target = "TfsBuildManager.Repository.BuildRetentionPolicy.#PartiallySucceededDeleteOptions")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1051:DoNotDeclareVisibleInstanceFields", Scope = "member", Target = "TfsBuildManager.Repository.BuildRetentionPolicy.#FailedDeleteOptions")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1051:DoNotDeclareVisibleInstanceFields", Scope = "member", Target = "TfsBuildManager.Repository.BuildRetentionPolicy.#FailedKeep")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1014:MarkAssembliesWithClsCompliant")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1800:DoNotCastUnnecessarily", Scope = "member", Target = "TfsBuildManager.Repository.TfsClientRepository.#CloneBuild(System.Uri,System.String,Microsoft.TeamFoundation.VersionControl.Client.BranchObject,Microsoft.TeamFoundation.VersionControl.Client.BranchObject)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Maintainability", "CA1506:AvoidExcessiveClassCoupling", Scope = "type", Target = "TfsBuildManager.Repository.TfsClientRepository")]
